### PR TITLE
Add Jasmine 2's fdescribe/fit

### LINKED ISSUE #12: fdescribe/fit
karma-jasmine >=0.3.4 now supports `fdescribe/fit` which are native Jasmine 2.x equivalents for `ddescribe`/`iit`. This task should catch them.

BTW, karma-jasmine 0.3.3 dropped `ddescribe`/`iit` as well... (https://github.com/karma-runner/karma-jasmine/issues/73) Not sure if that's a long-term plan but if it is then maybe the task name should be changed. ;)

### PR DESCRIPTION
**Pull request by mzgol**
Fix #12

### CODE REVIEW

**Comment by mzgol** [comment]
This fails Node 0.8 tests for unrelated reasons. The patch should be fine.

**Comment by btford** [comment]
LGTM. I added you as a contributor, so feel free to merge things yourself in the future.

**Comment by mzgol** [comment]
Thanks! Could you also give me rights to publish to npm so that I can publish patch releases with such minor fixes?

**Comment by btford** [comment]
what's your username for npm?

**Comment by mzgol** [comment]
Sorry, I forgot to write; it's m_gol

-- 
Michał Gołębiowski

**Comment by btford** [comment]
Added you!

**Comment by mzgol** [comment]
Thanks!

-- 
Michał Gołębiowski

**Pull request merged**
